CREATE TABLE BOOKINGS (
    ID NUMBER PRIMARY KEY,
    BOOKING_TYPE VARCHAR2(30) NOT NULL,
    SOURCE_FORM VARCHAR2(80) NOT NULL,
    FULL_NAME VARCHAR2(120) NOT NULL,
    MOBILE_NUMBER VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(255),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(20),
    DEPARTMENT VARCHAR2(120),
    DOCTOR_NAME VARCHAR2(120),
    CHECKUP_PACKAGE VARCHAR2(120),
    CONSULTATION_TYPE VARCHAR2(50),
    CONSULTATION_MODE VARCHAR2(50),
    PREFERRED_DATE DATE,
    PREFERRED_TIME_SLOT VARCHAR2(60),
    ALTERNATE_DATE DATE,
    SYMPTOMS CLOB,
    EXISTING_CONDITION VARCHAR2(10),
    PATIENT_ID VARCHAR2(80),
    BRANCH_LOCATION VARCHAR2(120),
    CITY VARCHAR2(120),
    INSURANCE_REQUIRED VARCHAR2(10),
    INSURANCE_PROVIDER VARCHAR2(120),
    WHATSAPP_UPDATES NUMBER(1) DEFAULT 0 NOT NULL,
    CONSENT NUMBER(1) DEFAULT 0 NOT NULL,
    NOTES CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT BOOKINGS_TYPE_CHECK CHECK (BOOKING_TYPE IN ('DOCTOR_APPOINTMENT', 'HEALTH_CHECKUP')),
    CONSTRAINT BOOKINGS_WHATSAPP_CHECK CHECK (WHATSAPP_UPDATES IN (0, 1)),
    CONSTRAINT BOOKINGS_CONSENT_CHECK CHECK (CONSENT IN (0, 1))
);

CREATE SEQUENCE BOOKINGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER BOOKINGS_BI
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT BOOKINGS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX BOOKINGS_TYPE_CREATED_AT_IDX ON BOOKINGS (BOOKING_TYPE, CREATED_AT DESC);
